#spring.application.name=administration
spring.application.name=UserService

# 1. Use localhost and port 1433
# Change 8080 to 1433
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=UserDatabase;encrypt=true;trustServerCertificate=true;
# 2. Credentials

spring.datasource.username=SpringUser
spring.datasource.password=Sandbox@123#

# 3. Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 4. EXPLICITLY set the Dialect (This fixes your specific error)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 5. Schema management
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true